-- ============================================================
-- V1 — Esquema inicial (PostgreSQL)
--
-- Generado a partir de las entidades JPA del proyecto con el
-- generador de esquema de Hibernate (dialecto PostgreSQL), y
-- luego revisado a mano para dar nombres legibles a las claves
-- foráneas (Hibernate las genera con hashes ilegibles).
--
-- A partir de acá el esquema lo gobierna Flyway: la aplicación
-- corre con ddl-auto=validate y NUNCA modifica tablas por su
-- cuenta. Todo cambio de entidad necesita una migración nueva.
-- ============================================================

CREATE TABLE usuarios (
    id_usuario  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario     VARCHAR(50)  NOT NULL,
    correo      VARCHAR(100),
    contrasenia VARCHAR(255) NOT NULL,
    imagen      VARCHAR(200) NOT NULL,
    PRIMARY KEY (id_usuario)
);

CREATE TABLE continentes (
    id_continente BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre        VARCHAR(255) NOT NULL,
    PRIMARY KEY (id_continente)
);

CREATE TABLE paises (
    id_pais       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre        VARCHAR(255),
    id_continente BIGINT NOT NULL,
    PRIMARY KEY (id_pais),
    CONSTRAINT fk_paises_continente FOREIGN KEY (id_continente) REFERENCES continentes
);

CREATE TABLE limites (
    id_limite BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_pais1  BIGINT NOT NULL,
    id_pais2  BIGINT NOT NULL,
    PRIMARY KEY (id_limite),
    CONSTRAINT fk_limites_pais1 FOREIGN KEY (id_pais1) REFERENCES paises,
    CONSTRAINT fk_limites_pais2 FOREIGN KEY (id_pais2) REFERENCES paises
);

CREATE TABLE objetivos (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    descripcion              VARCHAR(255),
    id_tipo_objetivo         VARCHAR(255) CHECK (id_tipo_objetivo IN ('SECRETO','GENERAL')),
    cantidad_paises_objetivo INTEGER,
    limitrofe                INTEGER,
    africa                   INTEGER,
    asia                     INTEGER,
    europa                   INTEGER,
    america_norte            INTEGER,
    america_sur              INTEGER,
    oceania                  INTEGER,
    color_enemigo            VARCHAR(255) CHECK (color_enemigo IN ('ROJO','AZUL','VERDE','NARANJA','AMARILLO','VIOLETA')),
    PRIMARY KEY (id)
);

CREATE TABLE tarjetas (
    id_tarjeta BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_pais    BIGINT NOT NULL,
    simbolo    VARCHAR(255) NOT NULL CHECK (simbolo IN ('GLOBO','GALEON','CANION','COMODIN')),
    PRIMARY KEY (id_tarjeta),
    CONSTRAINT fk_tarjetas_pais FOREIGN KEY (id_pais) REFERENCES paises
);

CREATE TABLE simbolos (
    id_simbolo BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo       VARCHAR(255),
    PRIMARY KEY (id_simbolo)
);

CREATE TABLE tipo_mensajes (
    id_tipo_mensaje BIGINT GENERATED BY DEFAULT AS IDENTITY,
    descripcion     VARCHAR(255),
    PRIMARY KEY (id_tipo_mensaje)
);

CREATE TABLE salas (
    id_sala     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre_sala VARCHAR(255) NOT NULL,
    url         VARCHAR(255),
    estado      VARCHAR(255) CHECK (estado IN ('ESPERANDO','INICIADA','FINALIZADA')),
    id_usuario  BIGINT,
    PRIMARY KEY (id_sala),
    CONSTRAINT fk_salas_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios
);

-- partidas, jugadores y turnos se referencian mutuamente. Se crean primero
-- sin esas FK y se agregan al final del archivo con ALTER TABLE.
CREATE TABLE partidas (
    id_partida     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_sala        BIGINT NOT NULL UNIQUE,
    fecha_inicio   DATE,
    hostilidad     BOOLEAN,
    turno_actual   INTEGER,
    ganador_id     BIGINT,
    estado_partida VARCHAR(255) CHECK (estado_partida IN ('TERMINADA','PAUSADA','EN_JUEGO')),
    fase_actual    VARCHAR(255) CHECK (fase_actual IN ('COLOCACION','HOSTILIDADES','FIN_TURNO')),
    PRIMARY KEY (id_partida),
    CONSTRAINT fk_partidas_sala FOREIGN KEY (id_sala) REFERENCES salas
);

CREATE TABLE turnos (
    id_turno          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nro_turno         INTEGER,
    reagrupado        BOOLEAN DEFAULT FALSE,
    inicio            TIMESTAMP(6),
    fase              VARCHAR(255) CHECK (fase IN ('ATAQUE','REAGRUPACION','INCORPORACION')),
    id_jugador        BIGINT,
    partida_id_partida BIGINT,
    PRIMARY KEY (id_turno),
    CONSTRAINT fk_turnos_partida FOREIGN KEY (partida_id_partida) REFERENCES partidas
);

CREATE TABLE jugadores (
    id_jugador          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre              VARCHAR(255) NOT NULL,
    color               VARCHAR(255) CHECK (color IN ('ROJO','AZUL','VERDE','NARANJA','AMARILLO','VIOLETA')),
    tipo_jugador        VARCHAR(255) CHECK (tipo_jugador IN ('BOT','HUMANO')),
    estado_jugador      VARCHAR(255) CHECK (estado_jugador IN ('ELIMINADO','INACTIVO','ACTIVO','GANADOR')),
    eliminado_por_color VARCHAR(255) CHECK (eliminado_por_color IN ('ROJO','AZUL','VERDE','NARANJA','AMARILLO','VIOLETA')),
    acepto_pausa        BOOLEAN,
    acepto_renudar      BOOLEAN,
    consquisto          BOOLEAN,
    finalizar_partida   BOOLEAN,
    perdio              BOOLEAN,
    ejercito            INTEGER,
    id_objetivo         BIGINT,
    id_partida          BIGINT,
    id_sala             BIGINT NOT NULL,
    id_turno            BIGINT,
    id_usuario          BIGINT,
    PRIMARY KEY (id_jugador),
    CONSTRAINT fk_jugadores_objetivo FOREIGN KEY (id_objetivo) REFERENCES objetivos,
    CONSTRAINT fk_jugadores_partida  FOREIGN KEY (id_partida)  REFERENCES partidas,
    CONSTRAINT fk_jugadores_sala     FOREIGN KEY (id_sala)     REFERENCES salas,
    CONSTRAINT fk_jugadores_turno    FOREIGN KEY (id_turno)    REFERENCES turnos,
    CONSTRAINT fk_jugadores_usuario  FOREIGN KEY (id_usuario)  REFERENCES usuarios
);

CREATE TABLE estadisticas (
    id_estadistica      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    eliminado           BOOLEAN,
    ganador             BOOLEAN,
    paises_conquistados INTEGER,
    paises_perdidos     INTEGER,
    rondas_jugadas      INTEGER,
    evento              VARCHAR(255),
    fecha_partida       VARCHAR(255),
    id_jugador          BIGINT NOT NULL,
    id_partida          BIGINT NOT NULL,
    PRIMARY KEY (id_estadistica),
    CONSTRAINT fk_estadisticas_jugador FOREIGN KEY (id_jugador) REFERENCES jugadores,
    CONSTRAINT fk_estadisticas_partida FOREIGN KEY (id_partida) REFERENCES partidas
);

CREATE TABLE estado_paises (
    id_estado_pais  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cantidad_tropas INTEGER,
    id_estadistica  BIGINT,
    id_jugador      BIGINT,
    id_pais         BIGINT NOT NULL,
    id_partida      BIGINT,
    PRIMARY KEY (id_estado_pais),
    CONSTRAINT fk_estado_paises_estadistica FOREIGN KEY (id_estadistica) REFERENCES estadisticas,
    CONSTRAINT fk_estado_paises_jugador     FOREIGN KEY (id_jugador)     REFERENCES jugadores,
    CONSTRAINT fk_estado_paises_pais        FOREIGN KEY (id_pais)        REFERENCES paises,
    CONSTRAINT fk_estado_paises_partida     FOREIGN KEY (id_partida)     REFERENCES partidas
);

CREATE TABLE estado_tarjetas (
    id_estado_tarjeta BIGINT GENERATED BY DEFAULT AS IDENTITY,
    canjeada          BOOLEAN NOT NULL,
    usada             BOOLEAN NOT NULL,
    fecha_asignacion  TIMESTAMP(6),
    id_jugador        BIGINT,
    id_partida        BIGINT,
    id_tarjeta        BIGINT NOT NULL,
    id_turno          BIGINT,
    PRIMARY KEY (id_estado_tarjeta),
    CONSTRAINT fk_estado_tarjetas_jugador FOREIGN KEY (id_jugador) REFERENCES jugadores,
    CONSTRAINT fk_estado_tarjetas_partida FOREIGN KEY (id_partida) REFERENCES partidas,
    CONSTRAINT fk_estado_tarjetas_tarjeta FOREIGN KEY (id_tarjeta) REFERENCES tarjetas,
    CONSTRAINT fk_estado_tarjetas_turno   FOREIGN KEY (id_turno)   REFERENCES turnos
);

CREATE TABLE jugadores_tarjetas (
    jugador_entity_id_jugador  BIGINT NOT NULL,
    tarjetas_id_estado_tarjeta BIGINT NOT NULL,
    CONSTRAINT fk_jugadores_tarjetas_jugador FOREIGN KEY (jugador_entity_id_jugador)  REFERENCES jugadores,
    CONSTRAINT fk_jugadores_tarjetas_tarjeta FOREIGN KEY (tarjetas_id_estado_tarjeta) REFERENCES estado_tarjetas
);

CREATE TABLE mensajes (
    id_mensaje      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    contenido       VARCHAR(255),
    id_jugador      BIGINT NOT NULL,
    id_partida      BIGINT NOT NULL,
    id_tipo_mensaje BIGINT NOT NULL,
    PRIMARY KEY (id_mensaje),
    CONSTRAINT fk_mensajes_jugador      FOREIGN KEY (id_jugador)      REFERENCES jugadores,
    CONSTRAINT fk_mensajes_partida      FOREIGN KEY (id_partida)      REFERENCES partidas,
    CONSTRAINT fk_mensajes_tipo_mensaje FOREIGN KEY (id_tipo_mensaje) REFERENCES tipo_mensajes
);

CREATE TABLE pactos (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo                   VARCHAR(255) CHECK (tipo IN ('PACTO_PAISES','PACTO_MUNDIAL','PACTO_ZONA_INTERNACIONAL')),
    estado                 VARCHAR(255) CHECK (estado IN ('PROPUESTO','ACTIVO','ROTO_VOLUNTARIO','ROTO_AUTOMATICO','RECHAZADO','EXPIRADO')),
    continente_zona        VARCHAR(255),
    turno_numero_al_romper INTEGER,
    fecha_propuesta        TIMESTAMP(6),
    fecha_aceptacion       TIMESTAMP(6),
    fecha_ruptura          TIMESTAMP(6),
    id_jugador_a           BIGINT,
    id_jugador_b           BIGINT,
    id_jugador_ruptura     BIGINT,
    id_pais_protegido_a    BIGINT,
    id_pais_protegido_b    BIGINT,
    id_pais_zona           BIGINT,
    id_partida             BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_pactos_jugador_a        FOREIGN KEY (id_jugador_a)        REFERENCES jugadores,
    CONSTRAINT fk_pactos_jugador_b        FOREIGN KEY (id_jugador_b)        REFERENCES jugadores,
    CONSTRAINT fk_pactos_pais_protegido_a FOREIGN KEY (id_pais_protegido_a) REFERENCES paises,
    CONSTRAINT fk_pactos_pais_protegido_b FOREIGN KEY (id_pais_protegido_b) REFERENCES paises,
    CONSTRAINT fk_pactos_pais_zona        FOREIGN KEY (id_pais_zona)        REFERENCES paises,
    CONSTRAINT fk_pactos_partida          FOREIGN KEY (id_partida)          REFERENCES partidas
);

-- FKs circulares, agregadas una vez que existen todas las tablas.
ALTER TABLE partidas
    ADD CONSTRAINT fk_partidas_ganador FOREIGN KEY (ganador_id) REFERENCES jugadores;

ALTER TABLE turnos
    ADD CONSTRAINT fk_turnos_jugador FOREIGN KEY (id_jugador) REFERENCES jugadores;
