##### Application properties #####
app.name=TEG-grupo8
app.desc=TEG project for Spring Boot
app.version=0.0.1-SNAPSHOT
app.url=http://localhost:8080
app.dev-name=John Doe
app.dev-email=dumy@dumy

##### SPRING DOC PROPERTIES #####
springdoc.show-actuator=true
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

##### SPRING DATA SOURCE (H2 persistente) #####
spring.datasource.url=jdbc:h2:file:./data/tegdb;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=100000
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

##### H2 Console #####
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

##### JPA / Hibernate #####
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
##### Inicialización de la base de datos #####
spring.sql.init.mode=never
spring.sql.init.platform=h2

##### Logging y servidor #####
server.port=8080
logging.level.root=WARN